// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Startawy.Infrastructure.Data;

#nullable disable

namespace Startawy.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316184058_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PackageStartupFounder", b =>
                {
                    b.Property<string>("FoundersUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PackagesPackageId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FoundersUserId", "PackagesPackageId");

                    b.HasIndex("PackagesPackageId");

                    b.ToTable("PackageStartupFounder");
                });

            modelBuilder.Entity("Startawy.Domain.Entities.Admin", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.Property<string>("AccessScope")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("access_scope");

                    b.Property<string>("AdminLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("admin_level");

                    b.HasKey("UserId");

                    b.ToTable("admin", (string)null);
                });

            modelBuilder.Entity("Startawy.Domain.Entities.Basic", b =>
                {
                    b.Property<string>("PackageId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("package_id");

                    b.Property<bool?>("UnlimitedAi")
                        .HasColumnType("bit")
                        .HasColumnName("unlimited_ai");

                    b.Property<bool?>("UnlimitedAnalysis")
                        .HasColumnType("bit")
                        .HasColumnName("unlimited_analysis");

                    b.HasKey("PackageId");

                    b.ToTable("basic", (string)null);
                });

            modelBuilder.Entity("Startawy.Domain.Entities.ChatBot", b =>
                {
                    b.Property<string>("ChatId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("chat_id");

                    b.Property<int?>("ChatLimit")
                        .HasColumnType("int")
                        .HasColumnName("chat_limit");

                    b.Property<string>("SysResponse")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sys_response");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2")
                        .HasColumnName("time");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.Property<string>("UserMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_message");

                    b.HasKey("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("chat_bot", (string)null);
                });

            modelBuilder.Entity("Startawy.Domain.Entities.Consultant", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.Property<string>("Availability")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("availability");

                    b.Property<string>("Certificate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("certificate");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("specialization");

                    b.Property<int?>("YearsOfExp")
                        .HasColumnType("int")
                        .HasColumnName("years_of_exp");

                    b.HasKey("UserId");

                    b.ToTable("consultant", (string)null);
                });

            modelBuilder.Entity("Startawy.Domain.Entities.Free", b =>
                {
                    b.Property<string>("PackageId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("package_id");

                    b.Property<int?>("FreeTrial")
                        .HasColumnType("int")
                        .HasColumnName("free_trial");

                    b.HasKey("PackageId");

                    b.ToTable("free", (string)null);
                });

            modelBuilder.Entity("Startawy.Domain.Entities.Package", b =>
                {
                    b.Property<string>("PackageId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("package_id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("PackageId");

                    b.ToTable("package", (string)null);
                });

            modelBuilder.Entity("Startawy.Domain.Entities.Premium", b =>
                {
                    b.Property<string>("PackageId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("package_id");

                    b.Property<bool?>("ConsultantReview")
                        .HasColumnType("bit")
                        .HasColumnName("consultant_review");

                    b.Property<bool?>("ConsultantSupport")
                        .HasColumnType("bit")
                        .HasColumnName("consultant_support");

                    b.Property<int?>("FollowUpDuration")
                        .HasColumnType("int")
                        .HasColumnName("follow_up_duration");

                    b.HasKey("PackageId");

                    b.ToTable("premium", (string)null);
                });

            modelBuilder.Entity("Startawy.Domain.Entities.Session", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("session_id");

                    b.Property<string>("ConsultantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("consultant_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("FounderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("founder_id");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.HasKey("SessionId");

                    b.HasIndex("ConsultantId");

                    b.HasIndex("FounderId");

                    b.ToTable("session", (string)null);
                });

            modelBuilder.Entity("Startawy.Domain.Entities.StartawyReport", b =>
                {
                    b.Property<string>("ReportId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("report_id");

                    b.Property<string>("FounderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("founder_id");

                    b.Property<string>("Industry")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("industry");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("link");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<DateOnly?>("UploadDate")
                        .HasColumnType("date")
                        .HasColumnName("upload_date");

                    b.HasKey("ReportId");

                    b.HasIndex("FounderId");

                    b.ToTable("startawy_reports", (string)null);
                });

            modelBuilder.Entity("Startawy.Domain.Entities.StartupFounder", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.Property<string>("BusinessName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("business_name");

                    b.Property<string>("BusinessSector")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("business_sector");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("FoundingDate")
                        .HasColumnType("date")
                        .HasColumnName("founding_date");

                    b.HasKey("UserId");

                    b.ToTable("startup_founder", (string)null);
                });

            modelBuilder.Entity("Startawy.Domain.Entities.Subscription", b =>
                {
                    b.Property<string>("SubsId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("subs_id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("PackageId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("package_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("TrialType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trial_type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("SubsId");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("subscription", (string)null);
                });

            modelBuilder.Entity("Startawy.Domain.Entities.Transaction", b =>
                {
                    b.Property<string>("TransId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("trans_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payment_method");

                    b.Property<string>("SubsId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("subs_id");

                    b.Property<DateOnly>("TransDate")
                        .HasColumnType("date")
                        .HasColumnName("trans_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("TransId");

                    b.HasIndex("SubsId");

                    b.HasIndex("UserId");

                    b.ToTable("transaction", (string)null);
                });

            modelBuilder.Entity("Startawy.Domain.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("UserId");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("startawy.Core.Entities.BudgetAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnalysisDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OptimizationPlan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recommendations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalExpenses")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRevenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("budget_analyses", (string)null);
                });

            modelBuilder.Entity("startawy.Core.Entities.BudgetLineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BudgetAnalysisId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("PlannedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BudgetAnalysisId");

                    b.ToTable("budget_line_items", (string)null);
                });

            modelBuilder.Entity("startawy.Core.Entities.CashFlowForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ForecastMonths")
                        .HasColumnType("int");

                    b.Property<decimal>("GrowthRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GrowthRecommendations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InitialCashBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Insights")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("MonthlyExpenseTrend")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyRevenueTrend")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProjectedRunway")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("cash_flow_forecasts", (string)null);
                });

            modelBuilder.Entity("startawy.Core.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("startawy.Core.Entities.ChatSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("chat_sessions", (string)null);
                });

            modelBuilder.Entity("startawy.Core.Entities.Competitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MarketResearchId")
                        .HasColumnType("int");

                    b.Property<double>("MarketShareEstimate")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strengths")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Weaknesses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MarketResearchId");

                    b.ToTable("competitors", (string)null);
                });

            modelBuilder.Entity("startawy.Core.Entities.ConsultationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedExpertId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpertNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PreAnalysis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("consultation_requests", (string)null);
                });

            modelBuilder.Entity("startawy.Core.Entities.DashboardSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BurnRate")
                        .HasColumnType("float");

                    b.Property<decimal>("CashBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("ChurnRate")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("CustomerAcquisitionCost")
                        .HasColumnType("float");

                    b.Property<int>("CustomerCount")
                        .HasColumnType("int");

                    b.Property<double>("CustomerLifetimeValue")
                        .HasColumnType("float");

                    b.Property<decimal>("Expenses")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("NetProfit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PredictiveInsights")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Revenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("dashboard_snapshots", (string)null);
                });

            modelBuilder.Entity("startawy.Core.Entities.FinancialStatement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalysisNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CostOfGoodsSold")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FinancingCashFlow")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossRevenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InvestingCashFlow")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("NetIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OperatingCashFlow")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OperatingExpenses")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PerformanceForecast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskAssessment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StatementDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAssets")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalLiabilities")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("financial_statements", (string)null);
                });

            modelBuilder.Entity("startawy.Core.Entities.MarketResearch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompetitorAnalysis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EstimatedMarketSize")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GeneratedReport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeographicScope")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("MarketGrowthRate")
                        .HasColumnType("float");

                    b.Property<string>("OpportunityInsights")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetMarket")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrendAnalysis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("market_researches", (string)null);
                });

            modelBuilder.Entity("startawy.Core.Entities.MarketTrend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImpactScore")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MarketResearchId")
                        .HasColumnType("int");

                    b.Property<string>("TrendName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MarketResearchId");

                    b.ToTable("market_trends", (string)null);
                });

            modelBuilder.Entity("startawy.Core.Entities.MarketingCampaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChannelRecommendations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentCalendar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetAudience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("marketing_campaigns", (string)null);
                });

            modelBuilder.Entity("startawy.Core.Entities.MonthlyForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CashFlowForecastId")
                        .HasColumnType("int");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CumulativeCashBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<decimal>("ProjectedExpenses")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProjectedRevenue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CashFlowForecastId");

                    b.ToTable("monthly_forecasts", (string)null);
                });

            modelBuilder.Entity("PackageStartupFounder", b =>
                {
                    b.HasOne("Startawy.Domain.Entities.StartupFounder", null)
                        .WithMany()
                        .HasForeignKey("FoundersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Startawy.Domain.Entities.Package", null)
                        .WithMany()
                        .HasForeignKey("PackagesPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Startawy.Domain.Entities.Admin", b =>
                {
                    b.HasOne("Startawy.Domain.Entities.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("Startawy.Domain.Entities.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Startawy.Domain.Entities.Basic", b =>
                {
                    b.HasOne("Startawy.Domain.Entities.Package", "Package")
                        .WithOne("Basic")
                        .HasForeignKey("Startawy.Domain.Entities.Basic", "PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Startawy.Domain.Entities.ChatBot", b =>
                {
                    b.HasOne("Startawy.Domain.Entities.User", "User")
                        .WithMany("ChatBots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Startawy.Domain.Entities.Consultant", b =>
                {
                    b.HasOne("Startawy.Domain.Entities.User", "User")
                        .WithOne("Consultant")
                        .HasForeignKey("Startawy.Domain.Entities.Consultant", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Startawy.Domain.Entities.Free", b =>
                {
                    b.HasOne("Startawy.Domain.Entities.Package", "Package")
                        .WithOne("Free")
                        .HasForeignKey("Startawy.Domain.Entities.Free", "PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Startawy.Domain.Entities.Premium", b =>
                {
                    b.HasOne("Startawy.Domain.Entities.Package", "Package")
                        .WithOne("Premium")
                        .HasForeignKey("Startawy.Domain.Entities.Premium", "PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Startawy.Domain.Entities.Session", b =>
                {
                    b.HasOne("Startawy.Domain.Entities.Consultant", "Consultant")
                        .WithMany("Sessions")
                        .HasForeignKey("ConsultantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Startawy.Domain.Entities.StartupFounder", "Founder")
                        .WithMany("Sessions")
                        .HasForeignKey("FounderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consultant");

                    b.Navigation("Founder");
                });

            modelBuilder.Entity("Startawy.Domain.Entities.StartawyReport", b =>
                {
                    b.HasOne("Startawy.Domain.Entities.StartupFounder", "Founder")
                        .WithMany("StartawyReports")
                        .HasForeignKey("FounderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Founder");
                });

            modelBuilder.Entity("Startawy.Domain.Entities.StartupFounder", b =>
                {
                    b.HasOne("Startawy.Domain.Entities.User", "User")
                        .WithOne("StartupFounder")
                        .HasForeignKey("Startawy.Domain.Entities.StartupFounder", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Startawy.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("Startawy.Domain.Entities.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Startawy.Domain.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Startawy.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Startawy.Domain.Entities.Subscription", "Subs")
                        .WithMany("Transactions")
                        .HasForeignKey("SubsId");

                    b.HasOne("Startawy.Domain.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subs");

                    b.Navigation("User");
                });

            modelBuilder.Entity("startawy.Core.Entities.BudgetAnalysis", b =>
                {
                    b.HasOne("Startawy.Domain.Entities.Package", null)
                        .WithMany("BudgetAnalyses")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("startawy.Core.Entities.BudgetLineItem", b =>
                {
                    b.HasOne("startawy.Core.Entities.BudgetAnalysis", "BudgetAnalysis")
                        .WithMany("LineItems")
                        .HasForeignKey("BudgetAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetAnalysis");
                });

            modelBuilder.Entity("startawy.Core.Entities.ChatMessage", b =>
                {
                    b.HasOne("startawy.Core.Entities.ChatSession", "ChatSession")
                        .WithMany("Messages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("startawy.Core.Entities.Competitor", b =>
                {
                    b.HasOne("startawy.Core.Entities.MarketResearch", null)
                        .WithMany("Competitors")
                        .HasForeignKey("MarketResearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("startawy.Core.Entities.MarketTrend", b =>
                {
                    b.HasOne("startawy.Core.Entities.MarketResearch", null)
                        .WithMany("Trends")
                        .HasForeignKey("MarketResearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("startawy.Core.Entities.MonthlyForecast", b =>
                {
                    b.HasOne("startawy.Core.Entities.CashFlowForecast", null)
                        .WithMany("MonthlyForecasts")
                        .HasForeignKey("CashFlowForecastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Startawy.Domain.Entities.Consultant", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Startawy.Domain.Entities.Package", b =>
                {
                    b.Navigation("Basic");

                    b.Navigation("BudgetAnalyses");

                    b.Navigation("Free");

                    b.Navigation("Premium");
                });

            modelBuilder.Entity("Startawy.Domain.Entities.StartupFounder", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("StartawyReports");
                });

            modelBuilder.Entity("Startawy.Domain.Entities.Subscription", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Startawy.Domain.Entities.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("ChatBots");

                    b.Navigation("Consultant");

                    b.Navigation("StartupFounder");

                    b.Navigation("Subscriptions");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("startawy.Core.Entities.BudgetAnalysis", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("startawy.Core.Entities.CashFlowForecast", b =>
                {
                    b.Navigation("MonthlyForecasts");
                });

            modelBuilder.Entity("startawy.Core.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("startawy.Core.Entities.MarketResearch", b =>
                {
                    b.Navigation("Competitors");

                    b.Navigation("Trends");
                });
#pragma warning restore 612, 618
        }
    }
}
